spring:
  application:
    name: ims
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local-h2
    #active: prod-db
    #active: prod


handlebars:
  suffix: .html
  cache: false
  expose-session-attributes: true